# Generated by Django 4.0.3 on 2022-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtype', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('schema', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=50)),
            ],
        ),
    ]
