# Generated by Django 4.0.3 on 2022-08-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbinfo',
            old_name='host',
            new_name='url',
        ),
    ]
