# Generated by Django 4.0.3 on 2022-08-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_host_dbinfo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbinfo',
            old_name='url',
            new_name='dburl',
        ),
    ]
