# Generated by Django 4.0.3 on 2022-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mol_props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_id', models.CharField(max_length=100)),
                ('smiles', models.CharField(max_length=1000)),
                ('mol', models.TextField()),
                ('MW', models.FloatField()),
                ('XLOGP', models.FloatField()),
                ('HBA', models.IntegerField(default=0)),
                ('HBD', models.IntegerField(default=0)),
                ('atom_num', models.IntegerField(default=0)),
                ('bond_num', models.IntegerField(default=0)),
                ('MOLFORMULA', models.CharField(max_length=200)),
                ('TPSA', models.FloatField()),
                ('img_file', models.CharField(max_length=500)),
            ],
        ),
    ]
