# Generated by Django 4.0.3 on 2022-08-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mol_registration', '0002_rename_xlogp_mol_props_xlogp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mol_props',
            name='HBA',
        ),
        migrations.RemoveField(
            model_name='mol_props',
            name='HBD',
        ),
        migrations.RemoveField(
            model_name='mol_props',
            name='MOLFORMULA',
        ),
        migrations.RemoveField(
            model_name='mol_props',
            name='atom_num',
        ),
        migrations.RemoveField(
            model_name='mol_props',
            name='bond_num',
        ),
    ]
