# Generated by Django 4.0.3 on 2022-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mol_registration', '0003_remove_mol_props_hba_remove_mol_props_hbd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mol_props',
            name='compound_id',
            field=models.CharField(max_length=50),
        ),
    ]
