# Generated by Django 4.0.3 on 2022-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfo',
            name='ticket',
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
