# Generated by Django 4.0.3 on 2022-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mol_props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_id', models.CharField(max_length=50)),
                ('smiles', models.CharField(max_length=1000)),
                ('mol', models.TextField()),
                ('MW', models.FloatField()),
                ('xlogp', models.FloatField()),
                ('TPSA', models.FloatField()),
                ('img_file', models.CharField(max_length=500)),
                ('fingerprint', models.TextField(default='')),
            ],
        ),
    ]
