# Generated by Django 4.0.3 on 2022-08-24 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mol_registration', '0002_rename_mol_mol_props_mol_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mol_props',
            name='mol_file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
